---
title: "STAT F611 Homework 01"
author: "Henry Agbi-Kaiser"
date: "`r Sys.Date()`"
output:
  bookdown::pdf_document2: 
              highlight:   
              toc: false
              latex_engine: xelatex
              extra_dependencies: ["geometry"]
              citation_package: natbib
geometry: legalpaper, left=1in, right=1in, top=1in, bottom=1in

header-includes:
  - \usepackage{changepage}
  - \usepackage{subcaption}
---


```{r, echo=FALSE, warning=FALSE}
library(TSA)
library(ggplot2)
```

\textbf{1.1} 
 Scatterplot of LA Rainfall versus Last Year’s LA Rainfall
```{r, echo=FALSE, warning=FALSE}
data(larain)
data<-data.frame(y=larain, x=zlag(larain))
p.larain <- ggplot(data = data, mapping = aes(x,y))+
  geom_point()+
  theme_bw()+
  xlab("Previous Year Inches")+
  ylab("Inches")
```


\textbf{1.2} 
Time Series Plot of Color Property from a Chemical Process
```{r, echo=FALSE, warning=FALSE}
data(color)
data<-data.frame(y=color, x= c(1:length(color)))
p.color <- ggplot(data = data, mapping = aes(x,y))+
  geom_line()+
  geom_point()+
  theme_bw()+
  xlab("Batch")+
  ylab("Color Property")
```


\textbf{1.5} 
```{r, echo=FALSE, warning=FALSE}
n <- 48
df <- 5
tdata <- rt(n, df)
data <- data.frame(y=tdata, x= c(1:length(tdata)))
p.t <- ggplot(data = data, mapping = aes(x,y))+
  geom_line()+
  geom_point()+
  theme_bw()+
  xlab("Time")+
  ylab("T")
```


\textbf{1.6}
Average Monthly Temperatures, Dubuque, Iowa
```{r, echo=FALSE, warning=FALSE}
data(tempdub)
data<-data.frame(y=tempdub, x=time(tempdub), s=as.vector(substr(season(tempdub),1,1)))
p.temdub <- ggplot(data = data, mapping = aes(x,y))+
  geom_line()+
  geom_text(aes(label=s))+
  theme_bw()+
  xlab("Time")+
  ylab("Temperature")
```

